convert_team_name = {  # NBA Pickem uses the city name, convert to full for bball_ref
    'Atlanta': 'Atlanta Hawks',
    'Boston': 'Boston Celtics',
    'Brooklyn': 'Brooklyn Nets',
    'Charlotte': 'Charlotte Hornets',
    'Chicago': 'Chicago Bulls',
    'Cleveland': 'Cleveland Cavaliers',
    'Dallas': 'Dallas Mavericks',
    'Denver': 'Denver Nuggets',
    'Detroit': 'Detroit Pistons',
    'Golden State': 'Golden State Warriors',
    'Houston': 'Houston Rockets',
    'Indiana': 'Indiana Pacers',
    'LA': 'Los Angeles Clippers',
    'Los Angeles': 'Los Angeles Lakers',
    'Memphis': 'Memphis Grizzlies',
    'Miami': 'Miami Heat',
    'Milwaukee': 'Milwaukee Bucks',
    'Minnesota': 'Minnesota Timberwolves',
    'New Orleans': 'New Orleans Pelicans',
    'New York': 'New York Knicks',
    'Oklahoma City': 'Oklahoma City Thunder',
    'Orlando': 'Orlando Magic',
    'Philadelphia': 'Philadelphia 76ers',
    'Phoenix': 'Phoenix Suns',
    'Portland': 'Portland Trail Blazers',
    'Sacramento': 'Sacramento Kings',
    'San Antonio': 'San Antonio Spurs',
    'Toronto': 'Toronto Raptors',
    'Utah': 'Utah Jazz',
    'Washington': 'Washington Wizards'
}



    # Artifacts: would need these to go to specific team's URL

    # 'Atlanta': 'ATL',
    # 'Boston': 'BOS',
    # 'Brooklyn': 'BRK',
    # 'Charlotte': 'CHA',
    # 'Chicago': 'CHI',
    # 'Cleveland': 'CLE',
    # 'Dallas': 'DAL',
    # 'Denver': 'DEN',
    # 'Detroit': 'DET',
    # 'Golden State': 'GSW',
    # 'Houston': 'HOU',
    # 'Indiana': 'IND',
    # 'LA': 'LAC',
    # 'Los Angeles': 'LAL',
    # 'Memphis': 'MEM',
    # 'Miami': 'MIA',
    # 'Milwaukee': 'MIL',
    # 'Minnesota': 'MIN',
    # 'New Orleans': 'NOP',
    # 'New York': 'NYK',
    # 'Oklahoma City': 'OKC',
    # 'Orlando': 'ORL',
    # 'Philadelphia': 'PHI',
    # 'Phoenix': 'PHO',
    # 'Portland': 'POR',
    # 'Sacramento': 'SAC',
    # 'San Antonio': 'SAS',
    # 'Toronto': 'TOR',
    # 'Utah': 'UTA',
    # 'Washington': 'WAS'
